# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='score_obtained',
            field=models.FloatField(default=0),
        ),
    ]
