# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='_correct',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='contest',
            name='timeout',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='filename',
            field=models.CharField(help_text='Setting this sets formatting in editor + filename for Java', max_length=50),
        ),
    ]
