# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_attempt_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
