# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20160115_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
